### ISSUE TITLE
logrotate fails

### ISSUE THREAD

**Issue by Phill93** [tschifftner/ansible-role-exim4-sendonly#2]
logrotate fails with this message:

`error: skipping "/var/mail/*" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.`

because folder is owned by root and the group is mail

```
root@test:/var/mail# ls -la
total 8
drwxrwsr-x  2 root mail 4096 Jun 21  2017 .
drwxr-xr-x 12 root root 4096 Feb 11 13:16 ..
```

**Comment by mr-jagannath** [comment]
@Phill93 
You have the answer in your error message itself. Try adding su option in your logrotate config
Ex: 
```
/var/mail
{
 su root mail
 #here logrotate acutal configuration 
}
 ```

**Comment by Phill93** [comment]
The role installs this logrotate config file. See pr #3
